name: Docker CI

on:
  push:
    branches:
      - main
      - develop
    # Build when a new version is tagged
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - develop
jobs:
#  build:
#    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
#    with:
#      image-name: "samply/feedback-hub-ui"
#      push-to: dockerhub
#    secrets:
#      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
